name: RecuperApp Continuous Delivery Pipeline

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, xdebug
          coverage: pcov

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Prepare Laravel environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: root
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
        run: vendor/bin/phpunit --stop-on-failure --stop-on-error --coverage-text

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          COMMIT_TAG=$(git rev-parse --short HEAD) && \
          docker build . -t ekyidag/recuperapp:$COMMIT_TAG -f ./Dockerfile

      - name: Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          COMMIT_TAG=$(git rev-parse --short HEAD) && \
          docker push ekyidag/recuperapp:$COMMIT_TAG

#      - name: Deploy to Kubernetes
#        uses: appleboy/kubectl-action@master
#        with:
#          args: set image deployment/recuperapp recuperapp=ekyidag/recuperapp:$COMMIT_TAG
#        env:
#          KUBECONFIG: ${{ secrets.KUBECONFIG }}
